# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# --- THEME SELECTION ---
# Sets user-defined palette.
# Palettes are defined at the bottom of the file.
palette = "catppuccin_macchiato"


# --- GENERAL CONFIG ---
add_newline = true
command_timeout = 2000

# --- PROMPT LAYOUT (Your original layout is preserved) ---
format = """
$os\
$username\
$directory\
$git_branch\
$git_commit\
$git_status\
$git_metrics\
$git_state\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$package\
$docker_context\
$kubernetes\
$container\
$jobs\
${custom.memory_usage}\
${custom.battery}\
${custom.keyboard_layout}\
$cmd_duration\
$status\
$line_break\
$character\
"""


# --- MODULE CONFIGURATION (Styled with Catppuccin Macchiato) ---

[os]
disabled = false
style = "peach"
format = '[$symbol]($style)'

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "peach"
style_root = "bold red"
format = '[ $user ]($style)'

[directory]
style = "bold lavender"
read_only_style = "lavender"
repo_root_style = "bold lavender"
format = "[ $path ]($style)"
read_only = " "
home_symbol = "~"
truncation_symbol = ""
truncation_length = 0
truncate_to_repo = true
fish_style_pwd_dir_length = 0
use_logical_path = true

[git_branch]
symbol = ""
style = "bold mauve"
format = '( [$symbol $branch]($style) )'
only_attached = true
ignore_branches = []
truncation_length = 25
truncation_symbol = "..."
always_show_remote = false
disabled = false

[git_commit]
style = "mauve"
format = "( [($tag)(@$hash)]($style) )"
commit_hash_length = 7
only_detached = true
tag_symbol = "󰓼 "
tag_disabled = false
disabled = false

[git_status]
style = "mauve"
format = '([$ahead_behind]($style) )([$all_status]($style) )'
stashed = "*${count}"
ahead = "⇡${count}"
behind = "⇣${count}"
up_to_date = ""
diverged = "⇡${ahead_count}⇣${behind_count}"
conflicted = "=${count}"
deleted = "×${count}"
renamed = "»${count}"
modified = "!${count}"
staged = "+${count}"
untracked = "?${count}"
ignore_submodules = false
disabled = false

[git_metrics]
format = '([([+$added]($added_style))([-$deleted]($deleted_style))](mauve) )'
added_style = "green"
deleted_style = "red"
only_nonzero_diffs = true
disabled = false

[git_state]
style = "red"
format = '([$state( $progress_current/$progress_total)]($style bold) )'
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
disabled = false

[nodejs]
symbol = ""
style = "teal"
format = '( [$symbol( $version)]($style) )'

[c]
symbol = ""
style = "teal"
format = '( [$symbol( $version)]($style) )'

[rust]
symbol = "󱘗"
style = "teal"
format = '( [$symbol( $version)]($style) )'

[golang]
symbol = "󰟓"
style = "teal"
format = '( [$symbol( $version)]($style) )'

[php]
symbol = ""
style = "teal"
format = '( [$symbol( $version)]($style) )'

[java]
symbol = ""
style = "teal"
format = '( [$symbol( $version)]($style) )'

[kotlin]
symbol = ""
style = "teal"
format = '( [$symbol( $version)]($style) )'

[haskell]
symbol = ""
style = "teal"
format = '( [$symbol( $version)]($style) )'

[python]
symbol = ""
style = "teal"
format = '( [$symbol( $version)( $virtualenv)]($style) )'
version_format = '${raw}'

[package]
disabled = false
symbol = "󰏗"
style = "teal"
format = '( [$symbol( $version)]($style) )'

[docker_context]
symbol = ""
style = "blue"
format = '( [$symbol( $context)]($style) )'

[kubernetes]
symbol = "󱃾"
style = "mauve"
format = '( [($symbol( $cluster))]($style) )'
disabled = false

[shell]
disabled = false
format = '[  $indicator ]($style)'
bash_indicator = "bash"
fish_indicator = "fish"
zsh_indicator = "zsh"
powershell_indicator = "powershell"
pwsh_indicator = "pwsh"
ion_indicator = "ion"
elvish_indicator = "elvish"
tcsh_indicator = "tcsh"
xonsh_indicator = "xonsh"
cmd_indicator = "cmd"
nu_indicator = "nu"
unknown_indicator = ""
style = "subtext0"

[container]
style = "flamingo"
format = '( [$symbol $name]($style) )'

[jobs]
symbol = "󰒋"
style = "text"
format = '( [$symbol( $number)]($style) )'
symbol_threshold = 1
number_threshold = 1

[memory_usage]
threshold = 0
symbol = "󰓅"
style = "text"
format = '( [$symbol( ${ram})]($style) )'
disabled = false

[battery]
full_symbol = "󰁹"
charging_symbol = "󰂄"
discharging_symbol = "󰂃"
unknown_symbol = "󰂑"
empty_symbol = "󰂎"
format = '( [$symbol( $percentage)]($style) )'
disabled = false

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 20
style = "yellow"

[[battery.display]]
threshold = 100
style = "text"

[time]
disabled = false
time_format = "%R"
style = "overlay1"
format = '( [󰔛 $time]($style) )'

[cmd_duration]
min_time = 2000
format = '( [󱫑 $duration]($style) )'
style = 'overlay1'
show_milliseconds = false
disabled = false

[status]
disabled = false
format = '( [$symbol( $common_meaning)( $signal_name)]($style) )'
map_symbol = true
pipestatus = true
symbol = '󰅙'
success_symbol = ''
not_executable_symbol = '󰂭'
not_found_symbol = '󰍉'
sigint_symbol = '󰐊'
signal_symbol = '󱐋'
style = 'bold red'
recognize_signal_code = true

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[[󰄛](green) ❯](peach)'
error_symbol = '[[󰄛](red) ❯](peach)'
vimcmd_symbol = '[❮](green)'
vimcmd_replace_one_symbol = '[❮](mauve)'
vimcmd_replace_symbol = '[❮](mauve)'
vimcmd_visual_symbol = '[❮](yellow)'


# --- CUSTOM MODULES ---

[custom.memory_usage]
command = "starship module memory_usage"
when = '[ "${STARSHIP_COCKPIT_MEMORY_USAGE_ENABLED:-false}" = "true" ]'
shell = "sh"
format = "( $output )"
disabled = false

[custom.battery]
command = """
battery_info=$(starship module battery)
if [ -n "$battery_info" ]; then
    percent=$(echo "$battery_info" | grep -o '[0-9]*%' | sed 's/%//')
    if [ "$percent" -le "${STARSHIP_COCKPIT_BATTERY_THRESHOLD:-0}" ]; then
        echo "$battery_info" | sed 's/%%/%/'
    fi
fi
"""
when = '[ "${STARSHIP_COCKPIT_BATTERY_ENABLED:-false}" = "true" ]'
shell = "sh"
format = "( $output )"
disabled = false

[custom.keyboard_layout]
command = """

# Set env variables if you want to use layout aliases (in uppercase)
#     export STARSHIP_COCKPIT_KEYBOARD_LAYOUT_ABC=ENG
#     export STARSHIP_COCKPIT_KEYBOARD_LAYOUT_UKRAINIAN=UKR
#
# Implementations:
#     macOS

if [ "$(uname -s)" = "Darwin" ]; then
        input_source=$(defaults read ~/Library/Preferences/com.apple.HIToolbox.plist AppleCurrentKeyboardLayoutInputSourceID)
        layout_id=$(echo "$input_source" | cut -d '.' -f4)
        layout=$(printenv "STARSHIP_COCKPIT_KEYBOARD_LAYOUT_$(echo "$layout_id" | tr '[:lower:]' '[:upper:]')")
        echo "$layout" || echo "$layout_id"
fi

"""
symbol = "󰌌"
style = "text"
format = '( [$symbol $output]($style) )'
when = '[ "${STARSHIP_COCKPIT_KEYBOARD_LAYOUT_ENABLED:-false}" = "true" ]'
shell = "sh"
disabled = false


# --- PALETTE DEFINITIONS (Catppuccin) ---

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"